version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:YOUR_APP_KEY
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
